# Generated by Django 3.0.7 on 2020-07-02 08:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
