# Generated by Django 3.0.7 on 2020-07-16 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_alertlog_alertstep_classname_productcampaign_result_scrapelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertlog',
            name='alert_step',
        ),
        migrations.DeleteModel(
            name='AlertStep',
        ),
    ]
