# Generated by Django 3.0.7 on 2020-06-22 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='active_from',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 13, 4, 32, 20393)),
        ),
    ]
