# Generated by Django 3.0.7 on 2020-06-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan_active_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='active_from',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
