# Generated by Django 3.0.7 on 2020-06-22 13:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loan_loan_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('principal', models.PositiveIntegerField()),
                ('tenure', models.PositiveIntegerField()),
                ('loan_id', models.UUIDField()),
                ('request_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
