# Generated by Django 3.0.7 on 2020-06-22 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_loanrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrequest',
            name='loan_id',
        ),
    ]
