# Generated by Django 3.0.7 on 2020-06-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_remove_loanrequest_loan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='loan_type',
            field=models.CharField(default='GPL', max_length=10),
            preserve_default=False,
        ),
    ]
