# Generated by Django 3.0.7 on 2020-06-24 13:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_auto_20200624_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('loan_type', models.CharField(max_length=3)),
                ('loan_type_long', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('principal', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tenure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('tenure', models.PositiveIntegerField()),
            ],
        )
    ]
