# Generated by Django 3.0.7 on 2020-06-24 13:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_auto_20200624_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('insurance_type', models.CharField(max_length=40)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='loan_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='base_interest',
            new_name='interest',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='redirect_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='active_from',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='installment_type',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='insurance_type',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_type',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='max_tenure',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='min_tenure',
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_type_id',
            field=models.ForeignKey(db_column='loan_type_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='loans.LoanType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='principal_id',
            field=models.ForeignKey(db_column='principal_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='loans.Principal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='tenure_id',
            field=models.ForeignKey(db_column='tenure_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='loans.Tenure'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LoanDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('installment_type', models.CharField(max_length=100)),
                ('insurance_id', models.ForeignKey(db_column='insurance_id', on_delete=django.db.models.deletion.CASCADE, to='loans.Insurance')),
                ('loan_id', models.ForeignKey(db_column='loan_id', on_delete=django.db.models.deletion.CASCADE, to='loans.Loan')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='bank_id',
            field=models.ForeignKey(db_column='bank_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='loans.Bank'),
            preserve_default=False,
        ),
    ]
