# Generated by Django 3.0.7 on 2020-06-24 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_auto_20200624_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantype',
            name='loan_type',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='loan_type_long',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tenure',
            name='tenure',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='loan_type',
            field=models.ForeignKey(db_column='loan_type_long', on_delete=django.db.models.deletion.CASCADE, to='loans.LoanType', to_field='loan_type_long'),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='tenure',
            field=models.ForeignKey(db_column='tenure', on_delete=django.db.models.deletion.CASCADE, to='loans.Tenure', to_field='tenure'),
        ),
    ]
