# Generated by Django 3.0.7 on 2020-06-24 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_auto_20200624_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='loan_type',
            field=models.ForeignKey(db_column='loan_type', on_delete=django.db.models.deletion.CASCADE, to='loans.LoanType', to_field='loan_type'),
        ),
    ]
