# Generated by Django 3.0.7 on 2020-06-24 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0014_auto_20200624_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='url',
        ),
        migrations.RemoveField(
            model_name='loandetail',
            name='insurance_id',
        ),
        migrations.RemoveField(
            model_name='loandetail',
            name='loan_id',
        ),
        migrations.AddField(
            model_name='loandetail',
            name='insurance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loans.Insurance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loandetail',
            name='loan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loans.Loan'),
            preserve_default=False,
        ),
    ]
