# Generated by Django 3.0.7 on 2020-06-24 15:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0015_auto_20200624_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('installment_type', models.CharField(max_length=40, unique=True)),
            ],
        ),
    ]
