# Generated by Django 3.0.7 on 2020-06-24 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0016_installmenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandetail',
            name='installment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.InstallmentType'),
        ),
    ]
