# Generated by Django 3.0.7 on 2020-06-25 11:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0017_auto_20200624_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('program', models.CharField(default='not_specified', max_length=40, unique=True)),
            ],
        ),
    ]
