# Generated by Django 3.0.7 on 2020-06-25 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0023_delete_loanlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('interest', models.FloatField()),
                ('upd_time', models.DateTimeField(auto_now_add=True, db_column='_upd_time')),
                ('bank', models.ForeignKey(db_column='bank_name', on_delete=django.db.models.deletion.CASCADE, to='loans.Bank', to_field='name')),
                ('loan_id', models.ForeignKey(db_column='loan_id', on_delete=django.db.models.deletion.PROTECT, to='loans.Loan')),
                ('loan_type', models.ForeignKey(db_column='loan_type', on_delete=django.db.models.deletion.CASCADE, to='loans.LoanType', to_field='loan_type')),
                ('principal', models.ForeignKey(db_column='principal', on_delete=django.db.models.deletion.CASCADE, to='loans.Principal', to_field='principal')),
                ('tenure', models.ForeignKey(db_column='tenure', on_delete=django.db.models.deletion.CASCADE, to='loans.Tenure', to_field='tenure')),
                ('upd_action', models.ForeignKey(db_column='_action', on_delete=django.db.models.deletion.PROTECT, to='loans.Action', to_field='action')),
                ('upd_program', models.ForeignKey(db_column='_program', on_delete=django.db.models.deletion.PROTECT, to='loans.Program', to_field='program')),
                ('upd_user', models.ForeignKey(db_column='_user', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
