# Generated by Django 3.0.7 on 2020-06-25 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0026_loanlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanlog',
            old_name='id',
            new_name='log_id',
        ),
        migrations.RemoveField(
            model_name='loanlog',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='loanlog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='loanlog',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='loanlog',
            name='loan_id',
        ),
        migrations.RemoveField(
            model_name='loanlog',
            name='loan_type',
        ),
        migrations.RemoveField(
            model_name='loanlog',
            name='name',
        ),
        migrations.RemoveField(
            model_name='loanlog',
            name='principal',
        ),
        migrations.RemoveField(
            model_name='loanlog',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='loanlog',
            name='tenure',
        ),
        migrations.RemoveField(
            model_name='loanlog',
            name='upd_program',
        ),
        migrations.RemoveField(
            model_name='loanlog',
            name='upd_time',
        ),
        migrations.RemoveField(
            model_name='loanlog',
            name='upd_user',
        ),
        migrations.AddField(
            model_name='loanlog',
            name='loan_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='loans.Loan'),
            preserve_default=False,
        ),
    ]
