# Generated by Django 3.0.7 on 2020-06-25 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0027_auto_20200625_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanlog',
            name='log_id',
        ),
        migrations.RemoveField(
            model_name='loanlog',
            name='upd_action',
        ),
        migrations.AlterField(
            model_name='loanlog',
            name='loan_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loans.Loan'),
        ),
    ]
