# Generated by Django 3.0.7 on 2020-06-25 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0028_auto_20200625_1618'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanLog',
        ),
    ]
