# Generated by Django 3.0.7 on 2020-06-25 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0029_delete_loanlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanLog',
            fields=[
                ('loan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loans.Loan')),
            ],
            bases=('loans.loan',),
        ),
    ]
