# Generated by Django 3.0.7 on 2020-06-25 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0035_auto_20200625_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.Bank'),
        ),
        migrations.AlterField(
            model_name='link',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.Loan'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='bank',
            field=models.ForeignKey(db_column='bank_name', on_delete=django.db.models.deletion.PROTECT, to='loans.Bank', to_field='name'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.ForeignKey(db_column='loan_type', on_delete=django.db.models.deletion.PROTECT, to='loans.LoanType', to_field='loan_type'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='principal',
            field=models.ForeignKey(db_column='principal', on_delete=django.db.models.deletion.PROTECT, to='loans.Principal', to_field='principal'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='tenure',
            field=models.ForeignKey(db_column='tenure', on_delete=django.db.models.deletion.PROTECT, to='loans.Tenure', to_field='tenure'),
        ),
        migrations.AlterField(
            model_name='loandetail',
            name='installment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.InstallmentType'),
        ),
        migrations.AlterField(
            model_name='loandetail',
            name='insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.Insurance'),
        ),
        migrations.AlterField(
            model_name='loandetail',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.Loan'),
        ),
        migrations.AlterField(
            model_name='loanlog',
            name='bank',
            field=models.ForeignKey(db_column='bank_name', on_delete=django.db.models.deletion.PROTECT, to='loans.Bank', to_field='name'),
        ),
        migrations.AlterField(
            model_name='loanlog',
            name='loan_type',
            field=models.ForeignKey(db_column='loan_type', on_delete=django.db.models.deletion.PROTECT, to='loans.LoanType', to_field='loan_type'),
        ),
        migrations.AlterField(
            model_name='loanlog',
            name='principal',
            field=models.ForeignKey(db_column='principal', on_delete=django.db.models.deletion.PROTECT, to='loans.Principal', to_field='principal'),
        ),
        migrations.AlterField(
            model_name='loanlog',
            name='tenure',
            field=models.ForeignKey(db_column='tenure', on_delete=django.db.models.deletion.PROTECT, to='loans.Tenure', to_field='tenure'),
        ),
    ]
