# Generated by Django 3.0.7 on 2020-06-25 15:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0036_auto_20200625_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanlog',
            name='log_id',
        ),
        migrations.AddField(
            model_name='loanlog',
            name='loan_id',
            field=models.ForeignKey(db_column='loan_id', default=uuid.UUID("60d6a9ea-9826-4c39-9ce5-38035fca852d"), on_delete=django.db.models.deletion.PROTECT, to='loans.Loan'),
            preserve_default=False,
        ),
    ]
