# Generated by Django 3.0.7 on 2020-06-25 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0038_auto_20200625_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanlog',
            name='loan_id',
            field=models.ForeignKey(db_column='loan_id', on_delete=django.db.models.deletion.PROTECT, to='loans.Loan'),
        ),
    ]
