# Generated by Django 3.0.7 on 2020-06-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0041_loandetaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='upd_time',
            field=models.DateTimeField(auto_now=True, db_column='_upd_time'),
        ),
        migrations.AlterField(
            model_name='loandetail',
            name='upd_time',
            field=models.DateTimeField(auto_now=True, db_column='_upd_time'),
        ),
        migrations.AlterField(
            model_name='loandetaillog',
            name='upd_time',
            field=models.DateTimeField(auto_now=True, db_column='_upd_time'),
        ),
        migrations.AlterField(
            model_name='loanlog',
            name='upd_time',
            field=models.DateTimeField(auto_now=True, db_column='_upd_time'),
        ),
    ]
