# Generated by Django 3.0.7 on 2020-06-26 09:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0043_auto_20200626_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandetaillog',
            name='upd_time',
            field=models.DateTimeField(db_column='_upd_time', default=datetime.datetime(2020, 6, 26, 9, 8, 30, 762665, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
