# Generated by Django 3.0.7 on 2020-06-26 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0044_loandetaillog_upd_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanDetailLog',
        ),
    ]
