# Generated by Django 3.0.7 on 2020-06-26 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0045_delete_loandetaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanDetailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('loan_detail_id', models.CharField(max_length=36)),
                ('upd_time', models.DateTimeField(db_column='_upd_time')),
                ('installment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.InstallmentType')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.Insurance')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.Loan')),
                ('upd_action', models.ForeignKey(db_column='_action', on_delete=django.db.models.deletion.PROTECT, to='loans.Action', to_field='action')),
                ('upd_program', models.ForeignKey(db_column='_program', on_delete=django.db.models.deletion.PROTECT, to='loans.Program', to_field='program')),
                ('upd_user', models.ForeignKey(db_column='_user', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
