# Generated by Django 3.0.7 on 2020-06-26 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0046_loandetaillog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loandetaillog',
            name='loan',
        ),
        migrations.AlterField(
            model_name='link',
            name='loan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='loans.Loan'),
        ),
        migrations.AlterField(
            model_name='loandetail',
            name='loan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='loans.Loan'),
        ),
    ]
