# Generated by Django 3.0.7 on 2020-06-26 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0047_auto_20200626_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='upd_program',
            field=models.ForeignKey(db_column='_program', default='not_specified', on_delete=django.db.models.deletion.PROTECT, to='loans.Program', to_field='program'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='upd_time',
            field=models.DateTimeField(auto_now=True, db_column='_upd_time'),
        ),
        migrations.AddField(
            model_name='link',
            name='upd_user',
            field=models.ForeignKey(db_column='_user', default='admin', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='username'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LinkLog',
            fields=[
                ('url', models.TextField()),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('loan_link_id', models.CharField(max_length=36)),
                ('upd_time', models.DateTimeField(db_column='_upd_time')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.Bank')),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='loans.Loan')),
                ('upd_action', models.ForeignKey(db_column='_action', on_delete=django.db.models.deletion.PROTECT, to='loans.Action', to_field='action')),
                ('upd_program', models.ForeignKey(db_column='_program', on_delete=django.db.models.deletion.PROTECT, to='loans.Program', to_field='program')),
                ('upd_user', models.ForeignKey(db_column='_user', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
