# Generated by Django 3.0.7 on 2020-06-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0049_auto_20200626_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linklog',
            name='loan',
            field=models.CharField(max_length=36),
        ),
    ]
