# Generated by Django 3.0.7 on 2020-06-26 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0050_auto_20200626_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='loan',
        ),
        migrations.RemoveField(
            model_name='linklog',
            name='loan',
        ),
        migrations.AddField(
            model_name='link',
            name='loan_type',
            field=models.ForeignKey(db_column='loan_type', default='GPL', on_delete=django.db.models.deletion.CASCADE, to='loans.LoanType', to_field='loan_type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linklog',
            name='loan_type',
            field=models.ForeignKey(db_column='loan_type', default='GPL', on_delete=django.db.models.deletion.CASCADE, to='loans.LoanType', to_field='loan_type'),
            preserve_default=False,
        ),
    ]
