# Generated by Django 3.0.7 on 2020-06-26 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0051_auto_20200626_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='bank',
            field=models.ForeignKey(db_column='bank_name', on_delete=django.db.models.deletion.PROTECT, to='loans.Bank', to_field='name'),
        ),
        migrations.AlterField(
            model_name='linklog',
            name='bank',
            field=models.ForeignKey(db_column='bank_name', on_delete=django.db.models.deletion.PROTECT, to='loans.Bank', to_field='name'),
        ),
    ]
