# Generated by Django 3.0.7 on 2020-06-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0052_auto_20200626_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='installmenttype',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='link',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='linklog',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loandetail',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loandetaillog',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loanlog',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loantype',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='principal',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='program',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenure',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
