# Generated by Django 3.0.7 on 2020-06-26 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0053_auto_20200626_1509'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('loan_type', 'bank')},
        ),
    ]
