# Generated by Django 3.0.7 on 2020-06-26 12:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0054_auto_20200626_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandetaillog',
            name='loan_id',
            field=models.CharField(default=uuid.UUID('c4d715da-b78f-11ea-affd-d0c63746edcc'), max_length=36),
            preserve_default=False,
        ),
    ]
