# Generated by Django 3.0.7 on 2020-06-26 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0055_loandetaillog_loan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='loan_type',
            field=models.ForeignKey(db_column='loan_type', on_delete=django.db.models.deletion.PROTECT, to='loans.LoanType', to_field='loan_type'),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='tenure',
            field=models.ForeignKey(db_column='tenure', on_delete=django.db.models.deletion.PROTECT, to='loans.Tenure', to_field='tenure'),
        ),
    ]
