# Generated by Django 3.0.7 on 2020-06-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0057_tenure_loan_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='tenure',
        ),
        migrations.AddField(
            model_name='loan',
            name='tenure',
            field=models.ManyToManyField(db_column='tenure', to='loans.Tenure'),
        ),
        migrations.RemoveField(
            model_name='loanlog',
            name='tenure',
        ),
        migrations.AddField(
            model_name='loanlog',
            name='tenure',
            field=models.ManyToManyField(db_column='tenure', to='loans.Tenure'),
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='tenure',
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='tenure',
            field=models.ManyToManyField(db_column='tenure', to='loans.Tenure'),
        ),
        migrations.AlterField(
            model_name='tenure',
            name='tenure',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='tenure',
            unique_together={('tenure', 'loan_type')},
        ),
    ]
