# Generated by Django 3.0.7 on 2020-06-26 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0058_auto_20200626_1801'),
    ]

    operations = [
    	migrations.AlterUniqueTogether(
            name='tenure',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tenure',
            name='loan_type',
        ),
    ]
