# Generated by Django 3.0.7 on 2020-06-26 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0059_auto_20200626_1807'),
    ]

    operations = [

        migrations.AlterField(
            model_name='tenure',
            name='tenure',
            field=models.PositiveIntegerField(unique=True),
        ),
        
        migrations.RemoveField(
            model_name='loan',
            name='tenure',
        ),
        
        migrations.RemoveField(
            model_name='loanlog',
            name='tenure',
        ),
        
        migrations.RemoveField(
            model_name='loanrequest',
            name='tenure',
        ),
        
        
    ]
