# Generated by Django 3.0.7 on 2020-06-26 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0061_auto_20200626_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrequest',
            name='loan_type',
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='loan_type_long',
            field=models.ForeignKey(db_column='loan_type_long', default='İhtiyaç Kredisi', on_delete=django.db.models.deletion.PROTECT, to='loans.LoanType', to_field='loan_type_long'),
            preserve_default=False,
        ),
    ]
