# Generated by Django 3.0.7 on 2020-06-26 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0062_auto_20200626_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrequest',
            name='loan_type_long',
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='loan_type',
            field=models.ForeignKey(db_column='loan_type', default='GPL', on_delete=django.db.models.deletion.PROTECT, to='loans.LoanType', to_field='loan_type'),
            preserve_default=False,
        ),
    ]
