# Generated by Django 3.0.7 on 2020-06-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0063_auto_20200626_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenure',
            name='loan_types',
            field=models.ManyToManyField(related_name='tenures', to='loans.LoanType'),
        ),
    ]
