# Generated by Django 3.0.7 on 2020-06-26 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0064_tenure_loan_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrequest',
            name='tenure',
        ),
    ]
