# Generated by Django 3.0.7 on 2020-06-26 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0065_remove_loanrequest_tenure'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='tenure',
            field=models.ForeignKey(db_column='tenure', default=12, on_delete=django.db.models.deletion.PROTECT, to='loans.Tenure', to_field='tenure'),
            preserve_default=False,
        ),
    ]
