# Generated by Django 3.0.7 on 2020-06-27 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0067_auto_20200627_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='allocation_cost',
            new_name='allocation_fee',
        ),
        migrations.RenameField(
            model_name='loanlog',
            old_name='allocation_cost',
            new_name='allocation_fee',
        ),
    ]
