# Generated by Django 3.0.7 on 2020-06-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0069_auto_20200627_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='logo_path',
            field=models.URLField(default='https://www.google.com'),
            preserve_default=False,
        ),
    ]
