# Generated by Django 3.0.7 on 2020-07-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0071_loansummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loansummary',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
