# Generated by Django 3.0.7 on 2020-07-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0072_auto_20200702_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansummary',
            name='url',
            field=models.TextField(default='https://www.ing.com.tr'),
            preserve_default=False,
        ),
    ]
