# Generated by Django 3.0.7 on 2020-07-06 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('loans', '0074_auto_20200706_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='logo_path',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
