# Generated by Django 3.0.7 on 2020-07-15 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0076_auto_20200706_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loansummary',
            old_name='interest',
            new_name='max_interest',
        ),
        migrations.RemoveField(
            model_name='loansummary',
            name='bank_logo_path',
        ),
        migrations.RemoveField(
            model_name='loansummary',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='loansummary',
            name='loan_name',
        ),
        migrations.RemoveField(
            model_name='loansummary',
            name='url',
        ),
        migrations.AddField(
            model_name='loansummary',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='loans.Bank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loansummary',
            name='loan_type',
            field=models.ForeignKey(db_column='loan_type', default=1, on_delete=django.db.models.deletion.PROTECT, to='loans.LoanType', to_field='loan_type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loansummary',
            name='min_interest',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loansummary',
            name='max_principal',
            field=models.ForeignKey(db_column='max_principal', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loans.Principal', to_field='principal'),
        ),
        migrations.AlterField(
            model_name='loansummary',
            name='max_tenure',
            field=models.ForeignKey(db_column='max_tenure', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loans.Tenure', to_field='tenure'),
        ),
        migrations.AlterField(
            model_name='loansummary',
            name='min_principal',
            field=models.ForeignKey(db_column='min_principal', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loans.Principal', to_field='principal'),
        ),
        migrations.AlterField(
            model_name='loansummary',
            name='min_tenure',
            field=models.ForeignKey(db_column='min_tenure', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loans.Tenure', to_field='tenure'),
        ),
    ]
