# Generated by Django 3.0.7 on 2020-07-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0077_auto_20200715_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_base',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanlog',
            name='is_base',
            field=models.BooleanField(default=False),
        ),
    ]
