# Generated by Django 3.0.7 on 2020-08-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0078_auto_20200715_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansummary',
            name='tenures',
            field=models.ManyToManyField(related_name='loan_summaries', to='loans.Tenure'),
        ),
    ]
