# Generated by Django 3.0.7 on 2020-08-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0079_loansummary_tenures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loansummary',
            name='id',
            field=models.CharField(max_length=109, primary_key=True, serialize=False),
        ),
    ]
