# Generated by Django 3.0.7 on 2020-08-07 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0082_bank_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_interest', models.FloatField()),
                ('date', models.DateField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.Bank')),
                ('loan_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loans.Loan')),
                ('loan_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loans.Loan')),
                ('loan_3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loans.Loan')),
                ('loan_type', models.ForeignKey(db_column='loan_type', on_delete=django.db.models.deletion.PROTECT, to='loans.LoanType', to_field='loan_type')),
                ('principal', models.ForeignKey(db_column='min_principal', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loans.Principal', to_field='principal')),
                ('tenure', models.ForeignKey(db_column='min_tenure', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loans.Tenure', to_field='tenure')),
            ],
        ),
    ]
