# Generated by Django 3.0.7 on 2020-08-07 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0083_loanmatrix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanmatrix',
            name='bank',
        ),
    ]
