# Generated by Django 3.0.7 on 2020-08-07 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0084_remove_loanmatrix_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanmatrix',
            name='loan_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loans.Loan'),
        ),
        migrations.AlterField(
            model_name='loanmatrix',
            name='loan_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loans.Loan'),
        ),
        migrations.AlterField(
            model_name='loanmatrix',
            name='loan_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loans.Loan'),
        ),
    ]
