# Generated by Django 3.0.7 on 2020-08-08 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0086_auto_20200808_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanMatrixTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_html', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('loan_type', models.ForeignKey(db_column='loan_type', on_delete=django.db.models.deletion.PROTECT, to='loans.LoanType', to_field='loan_type')),
            ],
        ),
    ]
