# Generated by Django 3.0.7 on 2020-08-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0088_bank_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='critical_loan_types',
            field=models.ManyToManyField(related_name='principals', to='loans.LoanType'),
        ),
    ]
