# Generated by Django 3.0.7 on 2020-08-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0089_principal_critical_loan_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='principal',
            name='critical_loan_types',
        ),
        migrations.AddField(
            model_name='loantype',
            name='critical_principals',
            field=models.ManyToManyField(related_name='loan_types', to='loans.Principal'),
        ),
    ]
