# Generated by Django 3.0.7 on 2020-08-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0091_auto_20200810_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanlog',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
