# Generated by Django 3.0.7 on 2020-08-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0092_auto_20200810_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='feature_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanlog',
            name='feature_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
