# Generated by Django 3.0.7 on 2020-07-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_subject', models.CharField(default='NA', max_length=240)),
                ('subject', models.CharField(default='NA', max_length=240)),
                ('child_subject', models.CharField(max_length=240)),
                ('content', models.TextField()),
            ],
        ),
    ]
