# Generated by Django 3.0.7 on 2020-07-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqitem',
            old_name='content',
            new_name='bullet_content',
        ),
        migrations.RenameField(
            model_name='faqitem',
            old_name='child_subject',
            new_name='bullet_no',
        ),
        migrations.AddField(
            model_name='faqitem',
            name='relevant_only_to',
            field=models.CharField(default='NA', max_length=240),
            preserve_default=False,
        ),
    ]
