# Generated by Django 3.0.7 on 2020-07-22 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_auto_20200722_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqitem',
            old_name='bullet_no',
            new_name='bullet',
        ),
    ]
