# Generated by Django 3.0.7 on 2020-07-22 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_auto_20200722_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqitem',
            old_name='relevant_only_to',
            new_name='relevant_to',
        ),
    ]
