# Generated by Django 3.0.7 on 2020-07-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0004_auto_20200722_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqitem',
            old_name='bullet',
            new_name='bullet_title',
        ),
        migrations.AddField(
            model_name='faqitem',
            name='bullet_no',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
